# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 14:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('reduce', models.CharField(max_length=100)),
                ('other', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='gatewaystate',
            name='task_name',
            field=models.CharField(max_length=50),
        ),
    ]
