# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GatewayAction',
        ),
    ]
