# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuySell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('forgn_b', models.IntegerField()),
                ('forgn_s', models.IntegerField()),
                ('forgn_n', models.IntegerField()),
                ('private_b', models.IntegerField()),
                ('private_s', models.IntegerField()),
                ('private_n', models.IntegerField()),
                ('inst_b', models.IntegerField()),
                ('inst_s', models.IntegerField()),
                ('inst_n', models.IntegerField()),
                ('trust_b', models.IntegerField()),
                ('trust_s', models.IntegerField()),
                ('trust_n', models.IntegerField()),
                ('pension_b', models.IntegerField()),
                ('pension_s', models.IntegerField()),
                ('pension_n', models.IntegerField()),
                ('etc_inst_b', models.IntegerField()),
                ('etc_inst_s', models.IntegerField()),
                ('etc_inst_n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('comm_cls_prc', models.IntegerField()),
                ('comm_stk_qty', models.IntegerField()),
                ('pref_stk_qty', models.IntegerField()),
                ('comm_stk_qty_af', models.IntegerField()),
                ('pref_stk_qty_af', models.IntegerField()),
                ('mkt_cap_comm', models.IntegerField()),
                ('mkt_cap', models.IntegerField()),
            ],
        ),
    ]
